In [1]:
import numpy as np
import matplotlib.pyplot as plt


# Initialisation

In [ ]:
#define architecture
input_size = 3
hidden_size = 5
output_size = 2

#define input, weights and biases
input_array = np.random.rand(1, input_size)

hidden_input = np.zeros((1, hidden_size))
hidden_weights = np.random.rand(input_size, hidden_size)
hidden_bias = np.random.rand(1, hidden_size)

output_input = np.zeros((1, output_size))
output_weights = np.random.rand(hidden_size, output_size)
output_bias = np.random.rand(1, output_size)

# For-Loop

In [33]:
#forward propagation
for i in range(hidden_size):
    for j in range(input_size):
        hidden_input[0][i] += input_array[0][j] * hidden_weights[j][i]
    hidden_input[0][i] += hidden_bias[0][i]
    hidden_input[0][i] = 1 / (1 + np.exp(-hidden_input[0][i]))

for i in range(output_size):
    for j in range(hidden_size):
        output_input[0, i] += hidden_input[0][j] * output_weights[j][i]
    output_input[0, i] += output_bias[0][i]
    output_input[0,i] =  1 / (1 + np.exp(-output_input[0][i]))

print(input_array)
print(hidden_input)
print(output_input)

[[0.31397706 0.28279007 0.10186578]]
[[0.82428953 0.85750183 0.87425954 0.89613637 0.91186049]]
[[0.99557603 0.98374724]]


# Dot Matrix Calculation

In [38]:
hidden_input = np.dot(input_array,hidden_weights) + hidden_bias
hidden_input = 1/(1 + np.exp(-hidden_input))

output_input = np.dot(hidden_input,output_weights) + output_bias
output_input = 1/(1 + np.exp(-output_input))

print(input_array)
print(hidden_input)
print(output_input)


[[0.31397706 0.28279007 0.10186578]]
[[0.67714584 0.72162982 0.74613158 0.78058828 0.80733293]]
[[0.97994688 0.93972235]]


# Batching

# Layer Classes, and classes in general